- name: Install To Do App on new web server
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install Git and Python
      yum:
        name:
          - git
          - python3
        state: present
      become: yes