- name: Install To Do App on new web server
  hosts: webservers
  remote_user: ec2-user

  tasks:
    - name: Install Git and Python
      yum:
        name:
          - git
          - python3
        state: present
      become: yes
    - name: Install Poetry
      shell:
        cmd: curl -sSL https://install.python-poetry.org | python3 -
        # make this not run all the time
    - name: Create To-Do App Directory
      file:
        path: /opt/todoapp
        state: directory
        mode: '777'
      become: yes
    - name: Checkout latest To-Do App code
      git:
        repo: 'https://github.com/josephsilcock/DevOps-Course-Starter.git'
        dest: /opt/todoapp
        version: module-4