services:
  todo-app:
    build: .
    ports:
      - 5000:5000
    env_file: ./.env
    volumes:
      - type: bind
        source: ./todo_app
        target: /todo-app/todo_app
    image: todo-app:dev
