name: Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 1 * * *"
jobs:
  deploy_docker:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Terraform
        run: terraform init